import Link from "next/link";
import { ArrowLeft, ArrowRight, Palette, ShieldCheck } from "lucide-react";
import { CodeBlockWithCopy } from "@/components/docs/code-block-with-copy";
import { PageHeader } from "@/components/docs/page-header";
import { GlassButton } from "@/registry/liquid-glass/glass-button";

export default function ThemingPage() {
  return (
    <div className="mx-auto max-w-4xl px-5 py-12 sm:px-8 lg:py-16">
      <PageHeader category="Customize" title="Theming" description="Start with the variables Ein UI actually exposes, then use component classes for changes that belong to one surface." />
      <section aria-labelledby="tokens" className="border-y border-white/10 py-8"><div className="flex items-start gap-4"><Palette className="mt-1 size-5 text-cyan-300" aria-hidden="true" /><div><h2 id="tokens" className="text-xl font-semibold text-white">Shared glass tokens</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/60">These variables are defined in `app/globals.css`. Override them in the consumer project’s global stylesheet or theme selector.</p></div></div><div className="mt-6"><CodeBlockWithCopy language="css" filename="app/globals.css" code={`:root {\n  --glass-bg: rgba(255, 255, 255, 0.1);\n  --glass-border: rgba(255, 255, 255, 0.2);\n  --glass-shadow: rgba(0, 0, 0, 0.37);\n  --glass-highlight: rgba(255, 255, 255, 0.2);\n  --glass-glow-cyan: rgba(6, 182, 212, 0.3);\n  --glass-glow-blue: rgba(59, 130, 246, 0.3);\n  --glass-glow-purple: rgba(168, 85, 247, 0.3);\n}`} /></div></section>
      <section aria-labelledby="placement" className="py-10"><h2 id="placement" className="text-xl font-semibold text-white">Where overrides belong</h2><div className="mt-5 grid gap-4 sm:grid-cols-3"><div className="border-l border-cyan-300/50 pl-4"><h3 className="font-medium text-white">Global</h3><p className="mt-2 text-sm leading-6 text-white/55">Use `:root` for the default visual system shared by every component.</p></div><div className="border-l border-violet-300/50 pl-4"><h3 className="font-medium text-white">Dark mode</h3><p className="mt-2 text-sm leading-6 text-white/55">Use `.dark` for darker surfaces and softer glows when your app toggles a class on the root.</p></div><div className="border-l border-white/30 pl-4"><h3 className="font-medium text-white">One component</h3><p className="mt-2 text-sm leading-6 text-white/55">Use `className` or a local selector when a single surface needs a different treatment.</p></div></div></section>
      <section aria-labelledby="example" className="border-t border-white/10 py-10"><h2 id="example" className="text-xl font-semibold text-white">Create a calmer glass surface</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/60">Reduce opacity and border contrast together. Blur needs a meaningful background behind it; it cannot create separation on its own.</p><div className="mt-5"><CodeBlockWithCopy language="css" filename="app/globals.css" code={`:root {\n  --glass-bg: rgba(255, 255, 255, 0.06);\n  --glass-border: rgba(255, 255, 255, 0.14);\n  --glass-glow-cyan: rgba(6, 182, 212, 0.18);\n}`} /></div></section>
      <section aria-labelledby="utility" className="border-t border-white/10 py-10"><h2 id="utility" className="text-xl font-semibold text-white">Variables and utility classes are different</h2><p className="mt-2 max-w-2xl text-sm leading-7 text-white/60">Some registry components use direct Tailwind utilities for local color, spacing, or layout. Changing a glass variable will not automatically replace every utility value. Use the component’s `className` API or edit the copied source when you need a local change.</p><div className="mt-5 flex gap-3 rounded-xl border border-amber-300/20 bg-amber-300/[0.05] p-4 text-sm leading-6 text-amber-100"><ShieldCheck className="mt-0.5 size-4 shrink-0" aria-hidden="true" />Check text and border contrast after changing transparency, especially over bright or busy backgrounds.</div></section>
      <div className="flex flex-col-reverse gap-3 border-t border-white/10 pt-6 sm:flex-row sm:items-center sm:justify-between"><Link href="/docs/installation"><GlassButton variant="ghost"><ArrowLeft className="mr-2 size-4" aria-hidden="true" />Installation</GlassButton></Link><Link href="/docs/dark-mode"><GlassButton variant="primary">Dark mode <ArrowRight className="ml-2 size-4" aria-hidden="true" /></GlassButton></Link></div>
    </div>
  );
}
